# Generated by Django 2.0.2 on 2018-03-20 00:05

import cours.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_nom', models.CharField(max_length=40, verbose_name='Nom du Categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_libelle', models.CharField(max_length=80, verbose_name='Libelle du Formation')),
                ('formation_prix', models.PositiveSmallIntegerField(verbose_name='Prix du Formation')),
                ('formation_bio', models.TextField(default='')),
                ('formation_image', models.ImageField(default='uploads/nao-une.jpg', upload_to=cours.models.file_name_formation)),
                ('formation_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Categories')),
            ],
            options={
                'verbose_name': 'Formation',
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_email', models.EmailField(max_length=254, verbose_name='Email du utilisateur')),
                ('utilisateur_nom', models.CharField(default='default', max_length=50, verbose_name='Nom du utilisateur')),
                ('utilisateur_prenom', models.CharField(default='default', max_length=50, verbose_name='Prenom du utilisateur')),
                ('utilisateur_image', models.ImageField(default='uploads/default.png', upload_to=cours.models.file_name_utis, verbose_name='Image du utilisateur')),
                ('utilisateur_statu', models.CharField(default='default', max_length=150, verbose_name='Statu Actuel du utilisateur')),
                ('utilisateur_mdp', models.CharField(default='default', max_length=50, verbose_name='Mote de passe du utilisateur')),
                ('utilisateur_genre', models.CharField(choices=[('H', 'Homme'), ('F', 'femme')], default='H', max_length=1, verbose_name='Sexe du utilisateur')),
                ('utilisateur_date_naissance', models.DateField(default=datetime.date.today, verbose_name='Date de naissance du utilisateur')),
                ('utilisateur_bio', models.TextField(default='', verbose_name='Bio utilisateur')),
                ('utilisateur_valid', models.BooleanField(default=False, verbose_name='est-il valide?')),
                ('utilisateur_code', models.IntegerField(default=0, verbose_name='nombre verification')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.AddField(
            model_name='formations',
            name='formation_utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cours.Utilisateurs'),
        ),
    ]
