# Generated by Django 2.0.2 on 2018-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='utilisateur_veut',
            field=models.CharField(choices=[('E', 'Lancer des cours'), ('P', 'Chercher des cours'), ('D', 'Les deux')], default='D', max_length=2, verbose_name="L'utilisateur veut "),
        ),
    ]
