# Generated by Django 2.0.2 on 2018-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_utilisateurs_utilisateur_veut'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='formation_slug',
            field=models.SlugField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
