# Generated by Django 2.0.2 on 2018-03-21 19:19

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_formations_formation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_image', models.ImageField(default='uploads/default.png', upload_to=cours.models.file_name_utis, verbose_name='Image du utilisateur')),
                ('utilisateur_statu', models.CharField(default='default', max_length=150, verbose_name='Statu Actuel du utilisateur')),
                ('utilisateur_code', models.IntegerField(default=0, verbose_name='nombre verification')),
                ('utilisateur_veut', models.CharField(choices=[('E', 'Lancer des cours'), ('P', 'Chercher des cours'), ('D', 'Les deux')], default='D', max_length=2, verbose_name="L'utilisateur veut ")),
                ('utilisateur_bio', models.TextField(default='', verbose_name='Bio utilisateur')),
            ],
        ),
    ]
