# Generated by Django 2.0.2 on 2018-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utilisateur_genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'femme')], default='H', max_length=1, verbose_name='Sexe du utilisateur'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utilisateur_nom',
            field=models.CharField(default='default', max_length=50, verbose_name='Nom du utilisateur'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utilisateur_prenom',
            field=models.CharField(default='default', max_length=50, verbose_name='Prenom du utilisateur'),
        ),
    ]
