# Generated by Django 2.0.2 on 2018-03-21 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_auto_20180321_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utilisateur_date_naissance',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de naissance du utilisateur'),
        ),
    ]
