# Generated by Django 2.0.2 on 2018-04-07 00:03

import cours.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_auto_20180321_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2018, 4, 7, 1, 3, 56, 204976))),
                ('approuver', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
        migrations.AlterField(
            model_name='formations',
            name='formation_image',
            field=models.ImageField(default='uploads/formation/default.png', upload_to=cours.models.file_name_formation),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentaires', to='cours.Formations'),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Utilisateurs'),
        ),
    ]
