# Generated by Django 2.0.2 on 2018-04-07 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_auto_20180407_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 16, 47, 34, 386571)),
        ),
    ]
