# Generated by Django 2.0.2 on 2018-04-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_auto_20180407_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 17, 1, 38, 571840)),
        ),
    ]
