# Generated by Django 2.0.2 on 2018-04-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0013_auto_20180407_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 17, 11, 19, 906352)),
        ),
    ]
