# Generated by Django 2.0.2 on 2018-04-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_auto_20180407_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formations',
            name='formation_prix',
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 18, 37, 59, 438394)),
        ),
    ]
