# Generated by Django 2.0.2 on 2018-04-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_auto_20180407_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='commentaires',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Commentaires',
        ),
    ]
