# Generated by Django 2.0.4 on 2018-04-10 16:43

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_auto_20180410_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitres',
            old_name='title',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='chapitres',
            name='image',
            field=models.ImageField(default=None, upload_to=cours.models.file_name_chapitre),
        ),
    ]
