# Generated by Django 2.0.4 on 2018-04-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0021_auto_20180410_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationsSuivis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapitre', models.PositiveIntegerField()),
                ('fini', models.BooleanField(default=False)),
                ('foramtion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='cours.Formations')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_suivis', to='cours.Utilisateurs')),
            ],
        ),
    ]
