# Generated by Django 2.0.4 on 2018-04-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_formationssuivis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationssuivis',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='cours.Chapitres'),
        ),
    ]
