# Generated by Django 2.0.4 on 2018-04-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0024_auto_20180413_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitres',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
