# Generated by Django 2.0.4 on 2018-04-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0025_chapitres_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formationssuivis',
            options={'verbose_name': 'Formation suivi'},
        ),
    ]
